### ISSUE TITLE
Refactoring of Ipopt class

### ISSUE THREAD

**Issue by ghost** [cureos/csipopt#1]
Rename `Ipopt` instance partial class to `IpoptProblem` and removed `sealed` directive.
Implement additional `IpoptProblem` constructor that takes native delegates as arguments.
Make `Dispose(bool)` method `virtual protected` to facilitate subclassing.
Have problem classes like HS071 inherit `IpoptProblem`.
Move static interop methods and delegates to static class `IpoptAdapter`.
Remove `SetIntermediateCallback` method from `IpoptProblem`; have inheriting classes setting `m_intermediate` in the constructor instead.
Consider making `SetScaling` method a `Scaling` property with a setter instead.

**Comment by cureos** [comment]
`SetIntermediateCallback` method maintained, but is also conditionally called in the constructor that is intended to be ued in subclassing.
`SetScaling` sets scaling for multiple parameters at once and is therefore best maintained as a method.
